name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Обновили версию здесь

      - name: set up JDK 17
        uses: actions/setup-java@v4 # Обновили версию здесь
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: npm install

      - name: Prepare Web Assets
        run: npm run build

      - name: Add Android
        run: npx cap add android

      - name: Sync
        run: npx cap sync

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4 # ВОТ ТУТ БЫЛА ОШИБКА, ТЕПЕРЬ V4
        with:
          name: VHS-Retro-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
